export enum OperationTypeEnum {
    ADD_CONTACT_US_QUERY = 'AddContactUs',
    GET_ALL_CONTACT_US = 'GetAllContactUs',
    CREATE_CAREER_QUERY = "CreateCareerQuary",
    GET_ALL_CAREER_QUERY = "GetAllCareerQuaries",
    LOGIN_SUCCESS = "LoginSuccess",
    ADD_META_KEYWORDS = "AddMetaKeywords",
    ADD_PORTFOLIO = "AddPortfolio",
    GET_ALL_PORTFOLIO = "AddPortfolio",
    ADD_TESTIMONIAL = "AddTestimonials",
    AUTH_FAILURE = "AuthFailure",
    NOT_FOUND = "NotFound",
    FORBIDDEN = "Forbidden",
    BAD_REQUEST = "BadRequest",
    INTERNAL_ERROR = "InternalError",
    SUCCESS_MSG = "SuccessMessage",
    FAILURE_MESSAGE = "FailureMessage",
    ACCESS_TOKEN_ERROR = "AccessTokenError",
    TOKEN_REFRESH = "TokenRefres"
}
